### ISSUE TITLE
Get license timed out occasionally

### ISSUE THREAD

**Issue by z-samuel** [storyprotocol/typescript-sdk#60]
The code for testing:
```
client.license.get({ licenseId: '77' }).then(({ data: license }) => {
  console.log(license);
});
```
Error of execution:
```
$ npx ts-node licenses/get.ts 
/Users/mymac/git/story-protocol-sdk-node-sample/node_modules/@story-protocol/core-sdk/dist/story-protocol-core-sdk.cjs.dev.js:431
    throw new Error("".concat(msg, ": ").concat(error.message));
          ^
Error: Failed to get license: timeout of 1000ms exceeded
    at handleError (/Users/mymac/git/story-protocol-sdk-node-sample/node_modules/@story-protocol/core-sdk/dist/story-protocol-core-sdk.cjs.dev.js:431:11)
    at LicenseClient._callee$ (/Users/mymac/git/story-protocol-sdk-node-sample/node_modules/@story-protocol/core-sdk/dist/story-protocol-core-sdk.cjs.dev.js:1215:15)
    at tryCatch (/Users/mymac/git/story-protocol-sdk-node-sample/node_modules/@story-protocol/core-sdk/dist/story-protocol-core-sdk.cjs.dev.js:138:16)
    at Generator.<anonymous> (/Users/mymac/git/story-protocol-sdk-node-sample/node_modules/@story-protocol/core-sdk/dist/story-protocol-core-sdk.cjs.dev.js:226:17)
    at Generator.throw (/Users/mymac/git/story-protocol-sdk-node-sample/node_modules/@story-protocol/core-sdk/dist/story-protocol-core-sdk.cjs.dev.js:167:21)
    at asyncGeneratorStep (/Users/mymac/git/story-protocol-sdk-node-sample/node_modules/@story-protocol/core-sdk/dist/story-protocol-core-sdk.cjs.dev.js:400:24)
    at _throw (/Users/mymac/git/story-protocol-sdk-node-sample/node_modules/@story-protocol/core-sdk/dist/story-protocol-core-sdk.cjs.dev.js:422:9)
```
The issue happens occasionally, maybe the 1000ms second is too short for getting license, or optimization is required.

**Comment by edisonz0718** [comment]
Timeout is increased to 5000ms
